/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VetementRouteImport } from './routes/vetement'
import { Route as TechnologieRouteImport } from './routes/technologie'
import { Route as JeuxVideoRouteImport } from './routes/jeux-video'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VetementRoute = VetementRouteImport.update({
  id: '/vetement',
  path: '/vetement',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologieRoute = TechnologieRouteImport.update({
  id: '/technologie',
  path: '/technologie',
  getParentRoute: () => rootRouteImport,
} as any)
const JeuxVideoRoute = JeuxVideoRouteImport.update({
  id: '/jeux-video',
  path: '/jeux-video',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/jeux-video': typeof JeuxVideoRoute
  '/technologie': typeof TechnologieRoute
  '/vetement': typeof VetementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/jeux-video': typeof JeuxVideoRoute
  '/technologie': typeof TechnologieRoute
  '/vetement': typeof VetementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/jeux-video': typeof JeuxVideoRoute
  '/technologie': typeof TechnologieRoute
  '/vetement': typeof VetementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/jeux-video' | '/technologie' | '/vetement'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/jeux-video' | '/technologie' | '/vetement'
  id: '__root__' | '/' | '/admin' | '/jeux-video' | '/technologie' | '/vetement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  JeuxVideoRoute: typeof JeuxVideoRoute
  TechnologieRoute: typeof TechnologieRoute
  VetementRoute: typeof VetementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vetement': {
      id: '/vetement'
      path: '/vetement'
      fullPath: '/vetement'
      preLoaderRoute: typeof VetementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technologie': {
      id: '/technologie'
      path: '/technologie'
      fullPath: '/technologie'
      preLoaderRoute: typeof TechnologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeux-video': {
      id: '/jeux-video'
      path: '/jeux-video'
      fullPath: '/jeux-video'
      preLoaderRoute: typeof JeuxVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  JeuxVideoRoute: JeuxVideoRoute,
  TechnologieRoute: TechnologieRoute,
  VetementRoute: VetementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
